package com.drdo.project.app.utils;

import com.drdo.project.app.entity.Project;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;

@SuppressWarnings(value = "all")
public class Form6PDF {

    private String username;
    private PdfPCell cell;
    private Logger logger = LoggerFactory.getLogger(Form1PDF.class);

    public void getPDF(Project project, HttpServletResponse response, HttpServletRequest request) throws IOException, DocumentException {
        Object principal = SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        if (principal instanceof UserDetails) {
            username = ((UserDetails) principal).getUsername();
        } else {
            username = principal.toString();
        }
        OutputStream os;
        os = response.getOutputStream();
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        Document document = new Document();
        response.setContentType("application/pdf");
        PdfWriter pdfWriter = PdfWriter.getInstance(document, byteArrayOutputStream);
        document.open();
        document.addCreationDate();
        document.addAuthor(username);
        document.addTitle(project.getProjectNo() + " PDC Extension");
        Paragraph heading = new Paragraph("STATEMENT OF CASE FOR PDC EXTENSION", new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD));
        heading.setAlignment(Element.ALIGN_CENTER);
        heading.setSpacingAfter(40);
        document.add(heading);
        PdfPTable pdfPTable = new PdfPTable(2);
        pdfPTable.setWidthPercentage(100);
        float[] columnWidths = {1f, 1f};
        pdfPTable.setWidths(columnWidths);
        cell = new PdfPCell(new Paragraph("1. Title of the Project"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph(project.getTitleOfProject()));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("2. Project/Programme no."));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph(project.getProjectNo()));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("3. Name of Lab"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph(project.getNodalLabName()));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("4. Sponsoring Agency"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph(request.getParameter("Sponsoring_Agency")));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("5. Sanction Cost (in Cr)"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("IC: " + String.valueOf(project.getTotalCost()) + "(FE)" + String.valueOf(project.getForeignExchange())));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("6. Date of Sanction"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph(String.valueOf(project.getSanctionDate())));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("7. Amount spent so far (in Cr)"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("Spent \t - IC" + request.getParameter("Amount_Spent_So_Far_Spent_IC")+ "(FE" + request.getParameter("Amount_Spent_So_Far_Spent_FE") +") \n\nCommitted - IC" + request.getParameter("Amount_Spent_So_Far_Commited_IC") +" (FE" + request.getParameter("Amount_Spent_So_Far_Commited_FE")+") \n\nIn Pipeline - IC" + request.getParameter("Amount_Spent_So_Far_Pipeline_IC") +" (FE" + request.getParameter("Amount_Spent_So_Far_Pipeline_FE") +")"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("8. PDC Original (subsequent if any)"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph(String.valueOf(project.getPdcList().get(0))));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("9. Revised PDC proposed with financial or any other implications"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph(request.getParameter("PDC_revised_Date_1")));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("10. Whether approval of fund sought/obtained for revision of PDC"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph());
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("11. Details of Additional funds required"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph());
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("12. Minutes of the monitoring committee meetings held so far and recommendations of the highest monitoring committee for PDC extension of the project"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph());
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("13. Defendable reasons (point wise) why the PDC could not be adhered"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph());
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("14. Word done so far with milestones achieved"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph());
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("15. Work to be carried out with revised milestones for the extended period of PDC"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph());
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("16. Revised PERT/Gantt Chart attached"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph());
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("17. New Monitoring mechanism proposed to avoid further PDC slippage"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph());
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph("18. Check list for submission of case for PDC extension duly signed by competent authority (enclosed/not enclosed)"));
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        cell = new PdfPCell(new Paragraph());
        cell.setPaddingBottom(20);
        cell.setBorder(Rectangle.NO_BORDER);
        pdfPTable.addCell(cell);
        document.add(pdfPTable);
        Paragraph paragraph = new Paragraph("Approved/Not Approved", new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD));
        paragraph.setAlignment(Element.ALIGN_CENTER);
        paragraph.setSpacingAfter(50);
        document.add(paragraph);
        paragraph = new Paragraph("(Laboratory Director)", new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD));
        paragraph.setSpacingAfter(100);
        paragraph.setAlignment(Element.ALIGN_CENTER);
        document.add(paragraph);
        paragraph = new Paragraph("(Competent Authority)", new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD));
        paragraph.setAlignment(Element.ALIGN_CENTER);
        document.add(paragraph);
        document.close();
        pdfWriter.close();
        response.setContentLength(byteArrayOutputStream.size());
        response.setHeader("Content-Disposition", "attachment; filename=" + project.getProjectNo() + "Form6.pdf");
        byteArrayOutputStream.writeTo(os);
        if (os!=null){
            os.flush();
            os.close();
        }
    }
}
